name: Release npm package

on: workflow_dispatch

env:
  frontend-dir: ./frontend

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Change the dir
        run: cd ./frontend

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 7

      - uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "pnpm"
          cache-dependency-path: ${{ env.frontend-dir }}/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install
        working-directory: ${{ env.frontend-dir }}

      - name: Release on NPM
        run: pnpm semantic-release
        working-directory: ${{ env.frontend-dir }}
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
