name: Test Frontend

on:
  push:
    branches: ["main", "beta"]
  pull_request:
    branches: ["main", "beta"]

env:
  NODE_VERSION: 18
  frontend-dir: ./frontend

jobs:
  lint-frontend:
    name: Lint
    runs-on: [ubuntu-latest]
    timeout-minutes: 5

    strategy:
      matrix:
        target: [js, hbs]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: ^7.17.1

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: ${{ env.frontend-dir }}/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: ${{ env.frontend-dir }}

      - name: Lint ${{ matrix.target }}
        run: pnpm lint:${{ matrix.target }}
        working-directory: ${{ env.frontend-dir }}

  test-frontend:
    name: Tests
    needs: [lint-frontend]
    runs-on: [ubuntu-latest]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: ^7.17.1

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
          cache-dependency-path: ${{ env.frontend-dir }}/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
        working-directory: ${{ env.frontend-dir }}

      - name: Run tests
        run: pnpm test
        working-directory: ${{ env.frontend-dir }}
        env:
          COVERAGE: true

      - name: upload coverage report to codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
